# ArgoCD Application with Image Updater Annotations
# This Application watches the deployment repo and ECR for image updates
# - To run ArgoCD dashboard, execute: kubectl port-forward svc/argocd-server -n argocd 8080:443
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-devops
  # Target namespace where ArgoCD application lives
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reggiegunawan88/fullstack-devops-deployment.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-devops-k0s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
