apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fullstack-devops-app.yaml
  - configs/argocd-image-updater-config.yaml
  - scripts/ecr-login-config.yaml
  - secrets/aws-ecr-secret.yaml
  - image-updater-cr.yaml
