apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-login-script
  namespace: argocd-image-updater-system
data:
  ecr-login.sh: |
    #!/bin/sh
    echo "AWS:$(aws ecr get-login-password --region us-east-1)"
